/**
 * Dumps the published guides to Lua tables for the addon.
 *
 * The addon cannot make network requests, so its guides travel embedded in the package.
 * They are generated from the content collections and never hand-written: a guide
 * maintained in two places drifts, and the step ids are the contract with stored progress.
 *
 * Run with `pnpm run addon:export`. The output is gitignored; it is produced at package
 * time and shipped in the CurseForge upload.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { load } from 'js-yaml';

import { professionSchema, levelingRouteSchema } from '../src/schemas/content';
import { stepSchema } from '../src/schemas/step';
import type { Step } from '../src/schemas/step';

const here = dirname(fileURLToPath(import.meta.url));
const CONTENT = join(here, '..', 'src', 'content');
const OUTPUT = join(here, '..', '..', 'addon', 'WowForeverCompanion', 'Guides');

const LOCALES = ['en', 'es'] as const;
type Locale = (typeof LOCALES)[number];

/** Lua long strings would break on a `]]` in the text, so quote and escape instead. */
function luaString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
  return `"${escaped}"`;
}

function luaStep(step: Step, indent: string): string {
  const parts = [
    `id = ${luaString(step.id)}`,
    `from = ${step.from}`,
    `to = ${step.to}`,
    `action = ${luaString(step.action)}`,
  ];

  if (step.materials !== undefined && step.materials.length > 0) {
    const materials = step.materials
      .map((material) => `{ item = ${luaString(material.item)}, quantity = ${material.quantity} }`)
      .join(', ');
    parts.push(`materials = { ${materials} }`);
  }
  if (step.note !== undefined) parts.push(`note = ${luaString(step.note)}`);
  if (step.place !== undefined) {
    parts.push(
      `place = { zone = ${luaString(step.place.zone)}, x = ${step.place.x}, y = ${step.place.y} }`,
    );
  }

  return `${indent}{ ${parts.join(', ')} },`;
}

async function readFrontmatter(path: string): Promise<unknown> {
  const text = await readFile(path, 'utf8');
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  return load(match === null ? text : match[1]);
}

async function entriesIn(collection: string, locale: Locale): Promise<unknown[]> {
  const directory = join(CONTENT, collection, locale);
  const files = await readdir(directory);
  return Promise.all(files.map((file) => readFrontmatter(join(directory, file))));
}

async function buildLocale(locale: Locale): Promise<string> {
  const professions = (await entriesIn('professions', locale)).map((raw) =>
    professionSchema.parse(raw),
  );
  const routes = (await entriesIn('levelingRoutes', locale)).map((raw) =>
    levelingRouteSchema.parse(raw),
  );

  const lines: string[] = [
    '-- Generated by `pnpm run addon:export`. Do not edit: your changes will be overwritten.',
    `-- Locale: ${locale}`,
    '',
    'local _, ns = ...',
    'ns.Guides = ns.Guides or {}',
    `ns.Guides[${luaString(locale)}] = {`,
    '  professions = {',
  ];

  for (const profession of professions.sort((a, b) =>
    a.translationKey.localeCompare(b.translationKey),
  )) {
    lines.push(`    [${luaString(profession.translationKey)}] = {`);
    lines.push(`      name = ${luaString(profession.name)},`);
    lines.push(`      kind = ${luaString(profession.kind)},`);
    lines.push('      steps = {');
    for (const step of profession.steps) lines.push(luaStep(stepSchema.parse(step), '        '));
    lines.push('      },');
    lines.push('    },');
  }

  lines.push('  },', '  leveling = {');

  for (const route of routes.sort((a, b) => a.faction.localeCompare(b.faction))) {
    lines.push(`    [${luaString(route.faction)}] = {`);
    lines.push('      segments = {');
    for (const segment of route.segments) {
      lines.push('        {');
      lines.push(`          from = ${segment.from},`);
      lines.push(`          to = ${segment.to},`);
      lines.push(`          zones = { ${segment.zones.map(luaString).join(', ')} },`);
      lines.push('          steps = {');
      for (const step of segment.steps) lines.push(luaStep(stepSchema.parse(step), '            '));
      lines.push('          },');
      lines.push('        },');
    }
    lines.push('      },');
    lines.push('    },');
  }

  lines.push('  },', '}', '');
  return lines.join('\n');
}

await mkdir(OUTPUT, { recursive: true });

for (const locale of LOCALES) {
  const lua = await buildLocale(locale);
  const path = join(OUTPUT, `${locale}.lua`);
  await writeFile(path, lua, 'utf8');
  console.log(`wrote ${path} (${(lua.length / 1024).toFixed(1)} KB)`);
}
